Add gh actions
radio-astro-tools/pvextractor pull request #103
Opened 2021-11-20 17:14 UTC by keflavich

I'd like to get tests running again.  I copied actions from spectral-cube.  I hope those are right.

2021-11-20 19:51 UTC, e-koch requested changes
The tox file needs to be updated in a few places.

Also can remove the travis.yml file.

2021-11-20 19:51 UTC, e-koch commented on .github/workflows/main.yml
> +            name: Python 3.9 with all non-visualization dependencies (except CASA)
Drop w/ + w/o CASA run

2021-11-20 19:51 UTC, e-koch commented on .github/workflows/main.yml
> +            toxenv: py39-test-novis-cov
`-novis` isn't defined in the tox file.

https://github.com/radio-astro-tools/pvextractor/blob/master/tox.ini#L3

py39 also needs to be added there.

2021-11-20 19:51 UTC, e-koch commented on .github/workflows/main.yml
> +            name: Python 3.6 with minimal dependencies and CASA
Drop w/ + w/o CASA run

2021-11-21 22:05 UTC, keflavich commented
@e-koch does this look good now?  Do we need to activate actions...

2021-11-22 02:40 UTC, e-koch commented
@keflavich I _think_ so.

I can't remember if actions should just start or not. Since this PR only affects CI, I'm in favour of merging and fixing CI issues in another PR once they're running.

2021-11-22 02:40 UTC, e-koch approved these changes

2021-11-22 14:15 UTC, keflavich commented
it's green on my side!

2021-11-22 14:16 UTC, merged